name: DiscordAuthPlus
version: '1.1'
main: MS.discordAuthPlus.DiscordAuthPlus
api-version: '1.21'

permissions:
  DiscordAuthPlus.reload:
    description: Reload Permission
    default: op
  DiscordAuthPlus.UnconnectUser:
    description: UnconnectUser Permission
    default: op
  DiscordAuthPlus.UserInfo:
    description: UserInfo Permission
    default: op
